extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  sourceType: module
env:
  es6: true
  node: true
rules:
  '@typescript-eslint/await-thenable': error
  '@typescript-eslint/camelcase': off
  '@typescript-eslint/explicit-function-return-type':
    - error
    - allowExpressions: true
  '@typescript-eslint/member-naming':
    - error
    - private: '^_'
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/no-unnecessary-type-assertion': error
  '@typescript-eslint/no-use-before-define':
    - error
    - functions: false
      typedefs: false
  '@typescript-eslint/no-useless-constructor': error
  '@typescript-eslint/prefer-includes': error
  '@typescript-eslint/prefer-string-starts-ends-with': error
  '@typescript-eslint/restrict-plus-operands': error
  '@typescript-eslint/semi': error
  '@typescript-eslint/unbound-method': error
  array-callback-return: error
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: always-multiline
  max-len:
    - error
    - ignoreComments: false
      ignoreStrings: false
      ignoreTemplateLiterals: false
      ignoreUrls: true
  no-console: 'off'
  no-dupe-class-members: 'off' # TypeScript method overloading
  no-else-return: error
  no-eval: error
  no-var: error
  object-shorthand: error
  operator-linebreak:
    - error
    - before
  prefer-const: error
  semi: 'off'
  yoda: error
