export const enum Key {
    attributes,
    connected_callback_insert_index,
    connected_callback,
    constructor_insert_index,
    constructor,
    need_getter,
    need_setter,
    needs_named_ref,
    needs_ref,
    setter_metadata,
    shadow_root,
    static_html,
    tag_name,
}
